// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/pose.proto

/*
Package pose is a generated protocol buffer package.

It is generated from these files:
	protobuf/pose.proto

It has these top-level messages:
	Pose
	Point3
	Quaternion
*/
package pose

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pose struct {
	Translation *Point3     `protobuf:"bytes,1,opt,name=translation" json:"translation,omitempty"`
	Rotation    *Quaternion `protobuf:"bytes,2,opt,name=rotation" json:"rotation,omitempty"`
}

func (m *Pose) Reset()                    { *m = Pose{} }
func (m *Pose) String() string            { return proto.CompactTextString(m) }
func (*Pose) ProtoMessage()               {}
func (*Pose) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Pose) GetTranslation() *Point3 {
	if m != nil {
		return m.Translation
	}
	return nil
}

func (m *Pose) GetRotation() *Quaternion {
	if m != nil {
		return m.Rotation
	}
	return nil
}

type Point3 struct {
	X float32 `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z" json:"z,omitempty"`
}

func (m *Point3) Reset()                    { *m = Point3{} }
func (m *Point3) String() string            { return proto.CompactTextString(m) }
func (*Point3) ProtoMessage()               {}
func (*Point3) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Point3) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Point3) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Point3) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

type Quaternion struct {
	Qw float32 `protobuf:"fixed32,1,opt,name=qw" json:"qw,omitempty"`
	Qx float32 `protobuf:"fixed32,2,opt,name=qx" json:"qx,omitempty"`
	Qy float32 `protobuf:"fixed32,3,opt,name=qy" json:"qy,omitempty"`
	Qz float32 `protobuf:"fixed32,4,opt,name=qz" json:"qz,omitempty"`
}

func (m *Quaternion) Reset()                    { *m = Quaternion{} }
func (m *Quaternion) String() string            { return proto.CompactTextString(m) }
func (*Quaternion) ProtoMessage()               {}
func (*Quaternion) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Quaternion) GetQw() float32 {
	if m != nil {
		return m.Qw
	}
	return 0
}

func (m *Quaternion) GetQx() float32 {
	if m != nil {
		return m.Qx
	}
	return 0
}

func (m *Quaternion) GetQy() float32 {
	if m != nil {
		return m.Qy
	}
	return 0
}

func (m *Quaternion) GetQz() float32 {
	if m != nil {
		return m.Qz
	}
	return 0
}

func init() {
	proto.RegisterType((*Pose)(nil), "Pose")
	proto.RegisterType((*Point3)(nil), "Point3")
	proto.RegisterType((*Quaternion)(nil), "Quaternion")
}

func init() { proto.RegisterFile("protobuf/pose.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcf, 0x31, 0xab, 0x83, 0x30,
	0x10, 0xc0, 0x71, 0x92, 0x27, 0xbe, 0xc7, 0xf9, 0xe8, 0x90, 0x2e, 0x8e, 0xc5, 0xa5, 0xed, 0x62,
	0x41, 0xbf, 0x46, 0x07, 0x9b, 0xb1, 0x9b, 0x82, 0x05, 0xa1, 0xe4, 0x4c, 0x8c, 0x98, 0xe4, 0xd3,
	0x17, 0xcf, 0xd0, 0x76, 0xfc, 0x71, 0xf7, 0x3f, 0x38, 0xd8, 0x8f, 0x06, 0x2d, 0x76, 0xf3, 0xe3,
	0x32, 0xe2, 0xd4, 0x97, 0xa4, 0xe2, 0x0e, 0x49, 0x83, 0x53, 0x2f, 0xce, 0x90, 0x59, 0xd3, 0xaa,
	0xe9, 0xd9, 0xda, 0x01, 0x55, 0xce, 0x0e, 0xec, 0x94, 0x55, 0xbf, 0x65, 0x83, 0x83, 0xb2, 0xb5,
	0xfc, 0x9e, 0x89, 0x23, 0xfc, 0x19, 0xb4, 0xdb, 0x1e, 0xa7, 0xbd, 0xac, 0xbc, 0xcd, 0xad, 0xed,
	0x8d, 0x1a, 0x50, 0xc9, 0xf7, 0xb0, 0xa8, 0x20, 0xdd, 0x7a, 0xf1, 0x0f, 0xcc, 0xd1, 0x4d, 0x2e,
	0x99, 0x5b, 0xe5, 0xa9, 0xe4, 0x92, 0xf9, 0x55, 0x21, 0xff, 0xd9, 0x14, 0x8a, 0x2b, 0xc0, 0xe7,
	0x96, 0xd8, 0x01, 0xd7, 0x4b, 0x0c, 0xb9, 0x5e, 0xc8, 0x2e, 0xa6, 0x5c, 0x3b, 0xb2, 0x8f, 0x31,
	0xd7, 0x9e, 0x1c, 0xf2, 0x24, 0x3a, 0x74, 0x29, 0x3d, 0x59, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x52, 0xbe, 0xe5, 0x99, 0xfb, 0x00, 0x00, 0x00,
}
